### ISSUE TITLE
ch create for csci350 errors out, but run_scripts workflow works for some people

### ISSUE THREAD

**Issue by a-harhar** [camerondurham/cs350-docker#15]
**Describe the bug**

When running the ch command from [cs350-docker](https://github.com/camerondurham/cs350-docker) to create the csci350 container, it produces the following error:

`v1: Pulling from camerondurham/cs350-docker
Cannot create new environment. Error from Dockerfile build:
no matching manifest for linux/arm64/v8 in the manifest list entries`

**To Reproduce**

Simply using the ch create command from [cs350-docker](https://github.com/camerondurham/cs350-docker) causes this issue to appear. The issue states no manifest for linux/arm64/v8 -- I'm not entirely sure about this but I think it is attempting to use my host platform as the image's platform?

This issue does not occur when using the run_scripts workflow, which works completely fine! 

**Screenshots**

Running with `./run.sh start`:
<img width="1510" alt="image" src="https://github.com/camerondurham/ch/assets/40128340/b13e1e39-b83a-491c-9861-6b504791c485">

Running with `ch create`:
<img width="1512" alt="image" src="https://github.com/camerondurham/ch/assets/40128340/c716023d-29cc-4fc8-ae0d-6bf744fb9d17">

**Desktop (please complete the following information):**
- OS: MacOS v13.0.1
- Latest Docker Version (just updated)

**Additional context**
While run_scripts workflow is working for me, some other students are complaining that it doesn't work for them either. They are running into the same issue as before:

./run.sh start

Running Docker image

[+] Running 0/1

⠇ gdbserver Pulling                                                       2.9s

no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by a-harhar** [comment]
**UPDATE:**
Since this was a versioning issue with the platform, I had students change the docker-compose.yml file to add the following line:

`platform: linux/amd64`

The final file looks something like this:
<img width="413" alt="image" src="https://github.com/camerondurham/cs350-docker/assets/40128340/c9674472-0308-4e7c-b7bc-77b0f6c2e06d">

Seems like this worked for others facing this issue using the run_scripts workflow! However ch workflow is still not working and continues to run into the same issue

**Comment by camerondurham** [comment]
@a-harhar Thanks for bringing this up! You're right, I should have explicitly specified the required platform as you did and that's a bug. Feel free to PR the change to the Docker compose file or I'll do it after work.

And for `ch`, looks like not specifying  `platform: linux/amd64` in `ch` is a bug/feature required to make this config work, otherwise it will default to host platform that would be wrong for anything not x86.

**Comment by a-harhar** [comment]
Created a PR #16 for the issue. Thank you so much for your timely response, it is very much appreciated!

**Comment by camerondurham** [comment]
I'm going to close this after releasing your change in #16 to `ch` in version `v0.3.7`. Feel free to re-open if issues recur!

To upgrade, users can run `ch upgrade` for commands to upgrade to latest version. 

Example:
```
ch upgrade

        current version 0.3.7, latest version v0.3.7

        Please run the following upgrade command (detected macOS operating system):

        bash <(curl -s https://raw.githubusercontent.com/camerondurham/ch/main/scripts/install-ch.sh)

        For more help, see the repository README: https://github.com/camerondurham/ch
```

Users that installed via brew can upgrade with `brew upgrade camerondurham/tap/ch` to get the latest build and follow instructions in this repo.
